### ISSUE TITLE
adicionar mais de um veiculo

### ISSUE THREAD

**Issue by guilhermecespedes** [hudsonbrendon/sensor.drivvo#2]
Olá!

Eu tenho mais de um veiculo que gostaria de estar monitorando. Porem notei que quando tento realizar a adição deste segundo não funciona!

É alguma limitação mesmo da integração ou será que estou realizando algo errado?

A proposito, parabens pelo projeto!

**Comment by hudsonbrendon** [comment]
Pode me passar sua configuração? Fica melhor de te ajudar.
