### ISSUE TITLE
Last refill volume

### ISSUE THREAD

**Issue by FragMenthor** [hudsonbrendon/sensor.drivvo#22]
Hello!
Someway the last refill volume is missing from the attributes, I don't know the last version when it worked; I know I can make a sensor to calculate it (using unit price and total price paid), but it would make sense to be an attribute has it was. Is it possible, please, to reeintroduce it in the sensor again?
Thank you very much for your integration, and sorry for my english!

**Comment by sszemtelen** [comment]
Hello!
Yes please. Make it available for us again :)

Thanks for your work! :)
